### ISSUE TITLE
Not Up2Date or "minified": Missing AutoEQ Results

### ISSUE THREAD

**Issue by pitkz** [ThePBone/AutoEqPackages#1]
Hey,

I am using your Root Builds of JamesDSP and tried to check where the AutoEQ Data is pulled from and discovered your API and your Packages that sits behind it.
Im not sure if your Package is not Up2Date, or if you skip certain AutoEQ Results (as you write "Minified" in the Package description), but I can not find the same devices as in the AutoEQ Github files - f.e. the Beyerdynamic DT 1770.

Is there some way as user to trigger an update of the Package, or is it possible you that you can do so on a regular basis?

I would also appreciated to get explained what "Minified" does mean: What criterias do AutoEQ Results need to fullfil to be included, like to they need to be .txt, .csv or .wav, so I can see why my desired Headphone may not be included already?
Just by checking your files, it seems only GraphicEQ and CSV files are pulled, right?

Thanks

**Comment by timschneeb** [comment]
> Im not sure if your Package is not Up2Date

This repo itself is up-to-date; the AutoEQ repo was last updated on January 6th.

Updates get triggered daily at 4am UTC. You can inspect these automated tasks here: https://github.com/ThePBone/AutoEqPackages/actions

> Just by checking your files, it seems only GraphicEQ and CSV files are pulled, right?

Yes, exactly. This repo was initially built for the Linux port of JamesDSP (which uses the CSV files for visualization purposes), but I ended up reusing it for the Android web API.
Normally, all devices in the AutoEQ database should be included.

> I can not find the same devices as in the AutoEQ Github files - f.e. the Beyerdynamic DT 1770.

I checked the script that updates this repository, and it turns out it did not correctly handle special characters in the headphone/speaker name.
For example, files for the Beyerdynamic DT 1770 in the AutoEQ repo are called something like `Beyerdynamic DT 1770 (leatherette earpads)` and the parentheses symbols in the name caused it to get skipped when scanning the AutoEQ repository.

Anyway, the bug is now fixed. Thanks for reporting this issue! I refreshed the API, so the devices are now properly displayed in the app.
